feat: update-vra- adapter-cred-in-vrops
vmware-samples/power-validated-solutions-for-cloud-foundation pull request #28
Opened 2022-08-23 13:24 UTC by slakshmanan2706

In order to have a good experience with our community, we recommend that you read the [contributing guidelines](https://github.com/vmware-samples/power-validated-solutions-for-cloud-foundation/blob/main/CONTRIBUTING.md) for making a pull request.

**Summary of Pull Request**

Added function :  Update-vROPSvRAAdapterCredential 
Updated function : Undo-vROPSCredential 

#27

Signed-off-by: Lakshmanan Shanmugam <lshanmugam@vmware.com>

**Type of Pull Request**

- [ ] This is a bug fix.
- [x] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is something else.
      Please describe:

**Context of the Pull Request***

**Related to Existing Issues**

Closes : #27 

**Test and Documentation Coverage**

- [x] Tests have been completed (for bug fixes / features).
- [ ] Documentation has been added / updated (for bug fixes / features).

**Breaking Changes?**

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

2022-08-23 14:47 UTC, tenthirtyam requested changes
Great work! I've added a couple comments with suggestions for your consideration.

**Ryan Johnson**
Senior Staff Solutions Architect | Product Engineering @ VMware, Inc.

2022-08-23 14:47 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +        - Validates that vRealize Automation has been deployed in VMware Cloud Foundation aware mode and retrives its details
"retrieves"

2022-08-23 14:47 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +        [Parameter (Mandatory = $true)] [ValidateNotNullOrEmpty()] [String]$vRACredName,
Would it be more appropriate to use simplified parameters like:

- `credential_name` (or `credential_displayname`)
- `credential_username`
- `credential_password`

2022-08-23 14:47 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +                                        if ((Get-vROPSAdapter | Where-Object { $_.resourceKey.adapterKindKey -eq "CASAdapter" })) {
Instead of adding `-eq "CASAdapter"` here should we instead be passing in `-eq $adapterKind` where it's pulled from a default parameter?

2022-08-23 14:47 UTC, tenthirtyam commented on PowerValidatedSolutions.psm1
> +                                                                        "adapterKindKey" : "CASAdapter",
Instead of adding `"CASAdapter"` here should we instead be passing in `-eq $adapterKind` where it's pulled from a default parameter?

2022-08-24 15:20 UTC, tenthirtyam commented
Conflicts need to be resolved in the branch before we can merge into `main`.

2022-08-25 11:22 UTC, GaryJBlake reviewed
A few comments to address

2022-08-25 11:47 UTC, slakshmanan2706 commented on PowerValidatedSolutions.psm1
> +                                                        Write-Error "Validating vRealize Automation credential named ($vRACredName) in vRealize Operations Manager ($($vcfVropsDetails.loadBalancerFqdn
Done

2022-08-25 11:47 UTC, slakshmanan2706 commented on PowerValidatedSolutions.psm1
> +                                                        Write-Output "Updating vRealize Automation adapter named ($adapterName) in vRealize Operations Manager ($($vcfVropsDetails.loadBalancerFqdn)) :
Done

2022-08-25 11:48 UTC, slakshmanan2706 commented on PowerValidatedSolutions.psm1
> +                                                        Write-Output "Validating vRealize Automation credential named ($vRACredName) in vRealize Operations Manager ($($vcfVropsDetails.loadBalancerFqd
Done

2022-08-25 11:49 UTC, slakshmanan2706 commented on PowerValidatedSolutions.psm1
> +                                                    Write-Output "Adding vRealize Automation credential named ($vRACredName) in vRealize Operations Manager ($($vcfVropsDetails.loadBalancerFqdn)) : SU
Done

2022-08-25 13:02 UTC, closed without merging