Feat/integrate v ra with v rops
vmware-samples/power-validated-solutions-for-cloud-foundation pull request #88
Opened 2022-09-08 07:38 UTC by slakshmanan2706

Adds support for integrating vRealize Automation with vRealize Operations Manager

Adds the following cmdlets to support the same.

- New-vRAvROPSIntegrationItem
- Add-vRAIntegrationItem
- Test-vRAIntegrationItem
- Remove-vRAvROPSIntegration
- Undo-vRAvROPsIntegrationItem

Signed-off-by: Lakshmanan Shanmugam [lshanmugam@vmware.com](mailto:lshanmugam@vmware.com)

**Summary of Pull Request**

**Type of Pull Request**

- [ ] This is a bug fix.
- [x] This is an enhancement or feature.
- [ ] This is a code style / formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is something else.
      Please describe:

**Context of the Pull Request***

**Related to Existing Issues**

Closes #44  

**Test and Documentation Coverage**

- [x] Tests have been completed (for bug fixes / features).
- [ ] Documentation has been added / updated (for bug fixes / features).

**Breaking Changes?**

- [ ] Yes, there are breaking changes.
- [x] No, there are no breaking changes.

2022-09-08 12:18 UTC, slakshmanan2706 commented on PowerValidatedSolutions.psm1
> +                                            Write-Output "vRealize Operations Manager Integration with name '$vropsIntegrationName' not found..."
Done

2022-09-08 12:56 UTC, slakshmanan2706 commented on PowerValidatedSolutions.psm1
> +    Catch {
Done

2022-09-08 14:47 UTC, GaryJBlake commented on PowerValidatedSolutions.psm1
> +            Write-Host "Error "$response.message
Chang Write-Host to Write-Error

2022-09-08 15:39 UTC, tenthirtyam requested changes
Some minor changes requested. 😄

2022-09-08 17:11 UTC, tenthirtyam requested changes
@slakshmanan2706 - the changes look **great**, thank you!

One last minor item I noticed in this review - could you update the example passwords to conform to the other examples?

- from "VMw@re123!" to "VMw@re1!"
- from "VMware123!" to "VMw@re1!"

Thanks!
Ryan

2022-09-09 04:21 UTC, tenthirtyam approved these changes
LGTM! 🚀

2022-09-09 04:23 UTC, merged